{
    "name": "Hospital Management System",
    "author": "Rajesh",
    "license": "LGPL-3",
    "version": "19.0.1.0",
    "application": True,
    "sequence": -1,
    "depends":['base',
        'mail','contacts',
        'account',
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/patient_views.xml",
        "views/appointment_views.xml",
        "views/doctor_views.xml",
        "views/appointment_readonly_views.xml",
        "views/contact_move_views.xml",
        "views/menu.xml",
        "reports/appointment_report.xml",
    ],
}
